name = "mnc-cdn"
main = "src/index.ts"
compatibility_date = "2025-02-20"

routes = [
  { pattern = "cdn.mnc.achus.casa/*", zone_name = "achus.casa" }
]

[vars]
ALLOWED_ORIGIN = "https://mnc.achus.casa"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mnc-resources"
